### ISSUE TITLE
Have you done experiment on RotatE (also based on ns function)

### ISSUE THREAD

**Issue by HammerWang98** [rutgerswiselab/NS-KGE#1]
your idea was great, and efficient. I would like to know if you have done any other related work in the future. Because those KGE based on negative sampling will be invalid if you can varify the generality of no negative sampling.

**Comment by lzl65825** [comment]
I appreciate your interest. Currently, we do not have related work published.

I think I do not understand what you mean by saying those KGE will be invalid. Could you please provide more detail about it?
